import pptxgen from 'pptxgenjs';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { getTheme } from '../config/colorThemes.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * PowerPoint Generator Service
 * Creates professional PPT presentations from structured data
 *
 * Branding: InsightForge
 */

// Brand name constant
const BRAND_NAME = 'InsightForge';
const BRAND_TAGLINE = 'AI-Powered Business Intelligence';

/**
 * Generate PowerPoint presentation
 *
 * @param {Object} reportData - Complete report data with insights
 * @param {Object} insights - AI-generated insights
 * @param {string} themeId - Color theme ID (default, emerald, purple, slate, coral)
 * @returns {string} Path to generated PPT file
 */
export async function generatePPT(reportData, insights, themeId = 'default') {
  const { meta, metrics, charts, tables } = reportData;
  const COLORS = getTheme(themeId);

  // Create output directory if it doesn't exist
  const outputDir = path.join(__dirname, '..', 'generated');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Generate unique filename
  const timestamp = Date.now();
  const filename = `report_${meta.client.replace(/\s+/g, '_')}_${timestamp}.pptx`;
  const filepath = path.join(outputDir, filename);

  // Create presentation
  const pres = new pptxgen();

  // Set presentation properties
  pres.author = BRAND_NAME;
  pres.title = `${formatReportType(meta.reportType)} Report - ${meta.client}`;
  pres.subject = `${meta.reportType} Report for ${meta.period}`;
  pres.company = meta.client;

  // Define slide master with subtle footer line
  pres.defineSlideMaster({
    title: 'MASTER_SLIDE',
    background: { color: COLORS.white },
  });

  // Add slides with theme colors
  addTitleSlide(pres, meta, COLORS);
  addExecutiveSummarySlide(pres, insights, COLORS);
  addMetricsSlide(pres, metrics, COLORS);
  addInsightsSlide(pres, insights, COLORS);
  addChartSlides(pres, charts, COLORS);
  addDataSlide(pres, tables, COLORS);
  addClosingSlide(pres, meta, COLORS);

  // Save file
  await pres.writeFile({ fileName: filepath });

  return filename;
}

/**
 * Add title slide with premium design
 */
function addTitleSlide(pres, meta, COLORS) {
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  // Premium gradient-effect header (multiple layered bars)
  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 0,
    w: '100%',
    h: 1.8,
    fill: { color: COLORS.primary },
  });

  // Accent bar for visual depth
  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 1.8,
    w: '35%',
    h: 0.15,
    fill: { color: COLORS.accent },
  });

  // Decorative element
  slide.addShape(pres.ShapeType.rect, {
    x: '35%',
    y: 1.8,
    w: '15%',
    h: 0.15,
    fill: { color: COLORS.background },
  });

  // Main title
  slide.addText(formatReportType(meta.reportType) + ' Report', {
    x: 0.5,
    y: 2.2,
    w: '90%',
    h: 0.9,
    fontSize: 42,
    fontFace: 'Arial',
    color: COLORS.text,
    bold: true,
  });

  // Client name with accent underline
  slide.addText(meta.client, {
    x: 0.5,
    y: 3.1,
    w: '90%',
    h: 0.6,
    fontSize: 26,
    fontFace: 'Arial',
    color: COLORS.primary,
    bold: true,
  });

  // Period badge style
  slide.addShape(pres.ShapeType.roundRect, {
    x: 0.5,
    y: 3.8,
    w: 2.5,
    h: 0.4,
    fill: { color: COLORS.background },
  });

  slide.addText(meta.period, {
    x: 0.6,
    y: 3.85,
    w: 2.3,
    h: 0.3,
    fontSize: 14,
    fontFace: 'Arial',
    color: COLORS.text,
    bold: true,
  });

  // Date
  slide.addText(new Date(meta.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }), {
    x: 0.5,
    y: 4.4,
    w: '90%',
    h: 0.3,
    fontSize: 12,
    fontFace: 'Arial',
    color: COLORS.lightText,
  });

  // Footer with branding
  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 5.1,
    w: '100%',
    h: 0.02,
    fill: { color: COLORS.background },
  });

  slide.addText(`Generated by ${BRAND_NAME}`, {
    x: 0.5,
    y: 5.2,
    w: '90%',
    h: 0.3,
    fontSize: 10,
    fontFace: 'Arial',
    color: COLORS.lightText,
  });
}

/**
 * Add executive summary slide
 */
function addExecutiveSummarySlide(pres, insights, COLORS) {
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  // Header
  addSlideHeader(slide, 'Executive Summary', COLORS);

  // AI badge
  slide.addShape(pres.ShapeType.roundRect, {
    x: 0.5,
    y: 1.2,
    w: 0.8,
    h: 0.3,
    fill: { color: COLORS.accent },
  });

  slide.addText('AI', {
    x: 0.5,
    y: 1.22,
    w: 0.8,
    h: 0.26,
    fontSize: 10,
    fontFace: 'Arial',
    color: COLORS.white,
    bold: true,
    align: 'center',
  });

  // Summary text box with accent border
  slide.addShape(pres.ShapeType.roundRect, {
    x: 0.5,
    y: 1.6,
    w: 9,
    h: 1.4,
    fill: { color: COLORS.background },
    line: { color: COLORS.primary, width: 1.5 },
  });

  // Accent line on left
  slide.addShape(pres.ShapeType.rect, {
    x: 0.5,
    y: 1.6,
    w: 0.08,
    h: 1.4,
    fill: { color: COLORS.accent },
  });

  slide.addText(insights.executiveSummary, {
    x: 0.8,
    y: 1.75,
    w: 8.5,
    h: 1.1,
    fontSize: 15,
    fontFace: 'Arial',
    color: COLORS.text,
    valign: 'middle',
  });

  // Key points preview
  slide.addText('Key Findings', {
    x: 0.5,
    y: 3.15,
    w: 9,
    h: 0.4,
    fontSize: 16,
    fontFace: 'Arial',
    color: COLORS.primary,
    bold: true,
  });

  // First 3 insights as bullet points
  const bulletPoints = insights.keyInsights.slice(0, 3).map(insight => ({
    text: insight,
    options: {
      fontSize: 13,
      color: COLORS.text,
      bullet: { type: 'bullet', color: COLORS.primary },
      paraSpaceAfter: 6,
    },
  }));

  slide.addText(bulletPoints, {
    x: 0.5,
    y: 3.5,
    w: 9,
    h: 1.8,
    fontFace: 'Arial',
    valign: 'top',
  });

  addSlideFooter(slide, COLORS);
}

/**
 * Add key metrics slide with premium card design
 */
function addMetricsSlide(pres, metrics, COLORS) {
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  addSlideHeader(slide, 'Key Metrics', COLORS);

  // Display up to 6 metrics in a 2x3 grid
  const displayMetrics = metrics.slice(0, 6);
  const cols = 2;
  const boxWidth = 4.3;
  const boxHeight = 1.15;
  const startX = 0.5;
  const startY = 1.25;
  const gapX = 0.25;
  const gapY = 0.18;

  displayMetrics.forEach((metric, index) => {
    const col = index % cols;
    const row = Math.floor(index / cols);
    const x = startX + col * (boxWidth + gapX);
    const y = startY + row * (boxHeight + gapY);

    // Metric box with subtle shadow effect (background layer)
    slide.addShape(pres.ShapeType.roundRect, {
      x: x + 0.03,
      y: y + 0.03,
      w: boxWidth,
      h: boxHeight,
      fill: { color: 'E2E8F0' },
    });

    // Main metric box
    slide.addShape(pres.ShapeType.roundRect, {
      x,
      y,
      w: boxWidth,
      h: boxHeight,
      fill: { color: COLORS.white },
      line: { color: COLORS.background, width: 1 },
    });

    // Left accent bar
    slide.addShape(pres.ShapeType.rect, {
      x,
      y: y + 0.15,
      w: 0.06,
      h: boxHeight - 0.3,
      fill: { color: COLORS.primary },
    });

    // Metric name
    slide.addText(metric.name, {
      x: x + 0.2,
      y: y + 0.12,
      w: boxWidth - 0.4,
      h: 0.32,
      fontSize: 11,
      fontFace: 'Arial',
      color: COLORS.lightText,
    });

    // Metric value
    slide.addText(formatValue(metric.value, metric.unit), {
      x: x + 0.2,
      y: y + 0.5,
      w: boxWidth - 0.4,
      h: 0.5,
      fontSize: 26,
      fontFace: 'Arial',
      color: COLORS.text,
      bold: true,
    });
  });

  addSlideFooter(slide, COLORS);
}

/**
 * Add insights and recommendations slide with improved layout
 */
function addInsightsSlide(pres, insights, COLORS) {
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  addSlideHeader(slide, 'Insights & Recommendations', COLORS);

  // Left column - Key Insights with card style
  slide.addShape(pres.ShapeType.roundRect, {
    x: 0.4,
    y: 1.15,
    w: 4.5,
    h: 4,
    fill: { color: COLORS.background },
    line: { color: COLORS.primary, width: 0.5 },
  });

  slide.addText('Key Insights', {
    x: 0.55,
    y: 1.25,
    w: 4.2,
    h: 0.35,
    fontSize: 14,
    fontFace: 'Arial',
    color: COLORS.primary,
    bold: true,
  });

  const insightBullets = insights.keyInsights.map(insight => ({
    text: insight,
    options: {
      fontSize: 10,
      color: COLORS.text,
      bullet: { type: 'bullet', color: COLORS.primary },
      paraSpaceAfter: 4,
    },
  }));

  slide.addText(insightBullets, {
    x: 0.55,
    y: 1.65,
    w: 4.2,
    h: 3.4,
    fontFace: 'Arial',
    valign: 'top',
  });

  // Right column - Recommendations with card style
  if (insights.recommendations && insights.recommendations.length > 0) {
    slide.addShape(pres.ShapeType.roundRect, {
      x: 5.1,
      y: 1.15,
      w: 4.5,
      h: 1.8,
      fill: { color: COLORS.white },
      line: { color: COLORS.success, width: 0.5 },
    });

    slide.addText('Recommendations', {
      x: 5.25,
      y: 1.25,
      w: 4.2,
      h: 0.35,
      fontSize: 14,
      fontFace: 'Arial',
      color: COLORS.success,
      bold: true,
    });

    const recBullets = insights.recommendations.map(rec => ({
      text: rec,
      options: {
        fontSize: 10,
        color: COLORS.text,
        bullet: { type: 'bullet', color: COLORS.success },
        paraSpaceAfter: 3,
      },
    }));

    slide.addText(recBullets, {
      x: 5.25,
      y: 1.6,
      w: 4.2,
      h: 1.25,
      fontFace: 'Arial',
      valign: 'top',
    });
  }

  // Risk factors if present with card style
  if (insights.riskFactors && insights.riskFactors.length > 0) {
    const riskY = insights.recommendations?.length > 0 ? 3.05 : 1.15;

    slide.addShape(pres.ShapeType.roundRect, {
      x: 5.1,
      y: riskY,
      w: 4.5,
      h: 2.1,
      fill: { color: COLORS.white },
      line: { color: COLORS.danger, width: 0.5 },
    });

    slide.addText('Risk Factors', {
      x: 5.25,
      y: riskY + 0.1,
      w: 4.2,
      h: 0.35,
      fontSize: 14,
      fontFace: 'Arial',
      color: COLORS.danger,
      bold: true,
    });

    const riskBullets = insights.riskFactors.map(risk => ({
      text: risk,
      options: {
        fontSize: 10,
        color: COLORS.text,
        bullet: { type: 'bullet', color: COLORS.danger },
        paraSpaceAfter: 3,
      },
    }));

    slide.addText(riskBullets, {
      x: 5.25,
      y: riskY + 0.45,
      w: 4.2,
      h: 1.55,
      fontFace: 'Arial',
      valign: 'top',
    });
  }

  addSlideFooter(slide, COLORS);
}

/**
 * Add chart slides with themed colors
 */
function addChartSlides(pres, charts, COLORS) {
  if (!charts || charts.length === 0) return;

  charts.forEach(chart => {
    const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

    addSlideHeader(slide, chart.title, COLORS);

    // Convert chart data to pptxgenjs format
    const chartData = [{
      name: chart.yAxisLabel || 'Value',
      labels: chart.data.map(d => d.label),
      values: chart.data.map(d => d.value),
    }];

    // Map chart types
    const chartTypeMap = {
      bar: pres.ChartType.bar,
      line: pres.ChartType.line,
      pie: pres.ChartType.pie,
      doughnut: pres.ChartType.doughnut,
    };

    const pptChartType = chartTypeMap[chart.type] || pres.ChartType.bar;

    // Add chart with theme colors
    slide.addChart(pptChartType, chartData, {
      x: 0.5,
      y: 1.2,
      w: 9,
      h: 4,
      showLegend: chart.type === 'pie' || chart.type === 'doughnut',
      legendPos: 'r',
      showTitle: false,
      chartColors: COLORS.chartColors,
      barDir: 'bar',
      catAxisTitle: chart.xAxisLabel || '',
      valAxisTitle: chart.yAxisLabel || '',
      showCatAxisTitle: !!chart.xAxisLabel,
      showValAxisTitle: !!chart.yAxisLabel,
    });

    addSlideFooter(slide, COLORS);
  });
}

/**
 * Add data preview slide with themed table
 */
function addDataSlide(pres, tables, COLORS) {
  if (!tables || tables.length === 0) return;

  const table = tables[0];
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  addSlideHeader(slide, table.name || 'Data Preview', COLORS);

  // Prepare table data (max 5 columns, 8 rows for readability)
  const displayColumns = table.columns.slice(0, 5);
  const displayRows = table.rows.slice(0, 8);

  // Header row with theme color
  const headerRow = displayColumns.map(col => ({
    text: col,
    options: {
      fill: { color: COLORS.primary },
      color: COLORS.white,
      bold: true,
      fontSize: 10,
      align: 'center',
      valign: 'middle',
    },
  }));

  // Data rows with alternating backgrounds
  const dataRows = displayRows.map((row, rowIndex) =>
    displayColumns.map(col => ({
      text: String(row[col] ?? '-'),
      options: {
        fill: { color: rowIndex % 2 === 0 ? COLORS.background : COLORS.white },
        color: COLORS.text,
        fontSize: 9,
        align: 'center',
        valign: 'middle',
      },
    }))
  );

  const tableData = [headerRow, ...dataRows];

  // Calculate column widths
  const tableWidth = 9;
  const colWidth = tableWidth / displayColumns.length;

  slide.addTable(tableData, {
    x: 0.5,
    y: 1.3,
    w: tableWidth,
    colW: Array(displayColumns.length).fill(colWidth),
    rowH: 0.4,
    border: { type: 'solid', color: 'E2E8F0', pt: 0.5 },
    fontFace: 'Arial',
  });

  // Note about data
  slide.addText(`Showing ${displayRows.length} of ${table.rows.length} rows`, {
    x: 0.5,
    y: 5,
    w: 9,
    h: 0.3,
    fontSize: 10,
    fontFace: 'Arial',
    color: COLORS.lightText,
    italic: true,
  });

  addSlideFooter(slide, COLORS);
}

/**
 * Add closing slide with premium branding
 */
function addClosingSlide(pres, meta, COLORS) {
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  // Gradient-effect background with layered bars
  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 1.8,
    w: '100%',
    h: 2.4,
    fill: { color: COLORS.primary },
  });

  // Accent decorative element
  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 1.8,
    w: '100%',
    h: 0.1,
    fill: { color: COLORS.accent },
  });

  slide.addText('Thank You', {
    x: 0,
    y: 2.1,
    w: '100%',
    h: 0.8,
    fontSize: 40,
    fontFace: 'Arial',
    color: COLORS.white,
    bold: true,
    align: 'center',
  });

  slide.addText(meta.client, {
    x: 0,
    y: 2.9,
    w: '100%',
    h: 0.5,
    fontSize: 22,
    fontFace: 'Arial',
    color: COLORS.white,
    align: 'center',
  });

  // Period badge
  slide.addText(meta.period, {
    x: 0,
    y: 3.5,
    w: '100%',
    h: 0.35,
    fontSize: 14,
    fontFace: 'Arial',
    color: COLORS.white,
    align: 'center',
  });

  // Branding footer
  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 4.9,
    w: '100%',
    h: 0.02,
    fill: { color: COLORS.background },
  });

  slide.addText(BRAND_NAME, {
    x: 0,
    y: 5,
    w: '100%',
    h: 0.35,
    fontSize: 16,
    fontFace: 'Arial',
    color: COLORS.primary,
    bold: true,
    align: 'center',
  });

  slide.addText(BRAND_TAGLINE, {
    x: 0,
    y: 5.3,
    w: '100%',
    h: 0.25,
    fontSize: 10,
    fontFace: 'Arial',
    color: COLORS.lightText,
    align: 'center',
  });
}

// Helper functions

function addSlideHeader(slide, title, COLORS) {
  // Primary header bar
  slide.addShape('rect', {
    x: 0,
    y: 0,
    w: '100%',
    h: 0.08,
    fill: { color: COLORS.primary },
  });

  // Accent underline
  slide.addShape('rect', {
    x: 0,
    y: 0.08,
    w: '25%',
    h: 0.03,
    fill: { color: COLORS.accent },
  });

  slide.addText(title, {
    x: 0.5,
    y: 0.25,
    w: 9,
    h: 0.6,
    fontSize: 24,
    fontFace: 'Arial',
    color: COLORS.text,
    bold: true,
  });
}

function addSlideFooter(slide, COLORS) {
  // Footer line
  slide.addShape('rect', {
    x: 0.5,
    y: 5.25,
    w: 9,
    h: 0.01,
    fill: { color: COLORS.background },
  });

  slide.addText(`Generated by ${BRAND_NAME}`, {
    x: 0.5,
    y: 5.3,
    w: 4,
    h: 0.2,
    fontSize: 8,
    fontFace: 'Arial',
    color: COLORS.lightText,
  });
}

function formatReportType(type) {
  const types = {
    sales: 'Sales',
    financial: 'Financial',
    marketing: 'Marketing',
    inventory: 'Inventory',
    custom: 'Custom',
  };
  return types[type] || 'Business';
}

function formatValue(value, unit) {
  if (unit === '$') {
    return `$${value.toLocaleString()}`;
  }
  if (unit === '%') {
    return `${value}%`;
  }
  return `${value.toLocaleString()}${unit ? ' ' + unit : ''}`;
}

/**
 * Generate Comparison PowerPoint presentation
 *
 * @param {Object} comparison - Comparison data with summary and insights
 * @param {Object} aiInsights - AI-generated insights for the comparison
 * @param {Array} files - Array of file info objects
 * @param {string} themeId - Color theme ID
 * @returns {string} Filename of generated PPT
 */
export async function generateComparisonPPT(comparison, aiInsights, files, themeId = 'default') {
  const COLORS = getTheme(themeId);

  // Create output directory if it doesn't exist
  const outputDir = path.join(__dirname, '..', 'generated');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Generate unique filename
  const timestamp = Date.now();
  const filename = `comparison_report_${timestamp}.pptx`;
  const filepath = path.join(outputDir, filename);

  // Create presentation
  const pres = new pptxgen();

  // Set presentation properties
  pres.author = BRAND_NAME;
  pres.title = 'File Comparison Report';
  pres.subject = `Comparison: ${files[0]?.filename} vs ${files[1]?.filename}`;

  // Define slide master
  pres.defineSlideMaster({
    title: 'MASTER_SLIDE',
    background: { color: COLORS.white },
  });

  // Add slides with theme colors
  addComparisonTitleSlide(pres, files, COLORS);

  if (aiInsights?.summaryStatement) {
    addComparisonSummarySlide(pres, aiInsights, COLORS);
  }

  addComparisonMetricsSlide(pres, comparison, files, COLORS);

  if (aiInsights?.significantChanges?.length > 0) {
    addSignificantChangesSlide(pres, aiInsights, COLORS);
  }

  if (aiInsights?.recommendations?.length > 0 || aiInsights?.areasOfConcern?.length > 0) {
    addRecommendationsSlide(pres, aiInsights, COLORS);
  }

  addComparisonTableSlide(pres, comparison, files, COLORS);
  addComparisonClosingSlide(pres, files, COLORS);

  // Save file
  await pres.writeFile({ fileName: filepath });

  return filename;
}

/**
 * Add comparison title slide with premium design
 */
function addComparisonTitleSlide(pres, files, COLORS) {
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  // Premium header with accent
  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 0,
    w: '100%',
    h: 1.8,
    fill: { color: COLORS.primary },
  });

  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 1.8,
    w: '35%',
    h: 0.15,
    fill: { color: COLORS.accent },
  });

  // Main title
  slide.addText('File Comparison Report', {
    x: 0.5,
    y: 2.2,
    w: '90%',
    h: 0.9,
    fontSize: 40,
    fontFace: 'Arial',
    color: COLORS.text,
    bold: true,
  });

  // Files being compared
  slide.addText(`${files[0]?.filename || 'File 1'} vs ${files[1]?.filename || 'File 2'}`, {
    x: 0.5,
    y: 3.1,
    w: '90%',
    h: 0.6,
    fontSize: 18,
    fontFace: 'Arial',
    color: COLORS.primary,
    bold: true,
  });

  // Date
  slide.addText(new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }), {
    x: 0.5,
    y: 3.8,
    w: '90%',
    h: 0.3,
    fontSize: 12,
    fontFace: 'Arial',
    color: COLORS.lightText,
  });

  // AI badge
  slide.addShape(pres.ShapeType.roundRect, {
    x: 0.5,
    y: 4.3,
    w: 2.2,
    h: 0.4,
    fill: { color: COLORS.accent },
  });

  slide.addText('AI-Powered Analysis', {
    x: 0.5,
    y: 4.32,
    w: 2.2,
    h: 0.36,
    fontSize: 11,
    fontFace: 'Arial',
    color: COLORS.white,
    bold: true,
    align: 'center',
  });

  // Footer with branding
  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 5.1,
    w: '100%',
    h: 0.02,
    fill: { color: COLORS.background },
  });

  slide.addText(`Generated by ${BRAND_NAME}`, {
    x: 0.5,
    y: 5.2,
    w: '90%',
    h: 0.3,
    fontSize: 10,
    fontFace: 'Arial',
    color: COLORS.lightText,
  });
}

/**
 * Add AI summary slide
 */
function addComparisonSummarySlide(pres, aiInsights, COLORS) {
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  addSlideHeader(slide, 'AI Analysis Summary', COLORS);

  // AI badge
  slide.addShape(pres.ShapeType.roundRect, {
    x: 0.5,
    y: 1.2,
    w: 0.6,
    h: 0.3,
    fill: { color: COLORS.accent },
  });

  slide.addText('AI', {
    x: 0.5,
    y: 1.22,
    w: 0.6,
    h: 0.26,
    fontSize: 10,
    fontFace: 'Arial',
    color: COLORS.white,
    align: 'center',
    bold: true,
  });

  // Summary text box with accent border
  slide.addShape(pres.ShapeType.roundRect, {
    x: 0.5,
    y: 1.6,
    w: 9,
    h: 2,
    fill: { color: COLORS.background },
    line: { color: COLORS.primary, width: 1.5 },
  });

  // Accent line on left
  slide.addShape(pres.ShapeType.rect, {
    x: 0.5,
    y: 1.6,
    w: 0.08,
    h: 2,
    fill: { color: COLORS.accent },
  });

  slide.addText(aiInsights.summaryStatement, {
    x: 0.8,
    y: 1.8,
    w: 8.5,
    h: 1.6,
    fontSize: 15,
    fontFace: 'Arial',
    color: COLORS.text,
    valign: 'middle',
  });

  addSlideFooter(slide, COLORS);
}

/**
 * Add metrics overview slide
 */
function addComparisonMetricsSlide(pres, comparison, files, COLORS) {
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  addSlideHeader(slide, 'Metrics Overview', COLORS);

  // Transform summary data
  const metricChanges = Object.entries(comparison.summary || {}).map(([metric, data]) => {
    const labels = Object.keys(data).filter(k => !['absoluteChange', 'percentageChange', 'direction'].includes(k));
    return {
      metric: formatColumnName(metric),
      value1: data[labels[0]] || 0,
      value2: data[labels[1]] || 0,
      percentChange: data.percentageChange || 0,
      direction: data.direction || 'neutral',
    };
  });

  // Calculate stats
  const stats = {
    total: metricChanges.length,
    improved: metricChanges.filter(m => m.direction === 'up').length,
    declined: metricChanges.filter(m => m.direction === 'down').length,
    unchanged: metricChanges.filter(m => m.direction === 'neutral').length,
  };

  // Stats boxes
  const statsData = [
    { label: 'Metrics Compared', value: stats.total, color: COLORS.primary },
    { label: 'Improved', value: stats.improved, color: COLORS.success },
    { label: 'Declined', value: stats.declined, color: COLORS.danger },
    { label: 'Unchanged', value: stats.unchanged, color: COLORS.secondary },
  ];

  statsData.forEach((stat, index) => {
    const x = 0.5 + index * 2.4;

    slide.addShape(pres.ShapeType.roundRect, {
      x,
      y: 1.3,
      w: 2.2,
      h: 1.2,
      fill: { color: COLORS.background },
    });

    slide.addText(String(stat.value), {
      x,
      y: 1.4,
      w: 2.2,
      h: 0.7,
      fontSize: 32,
      fontFace: 'Arial',
      color: stat.color,
      bold: true,
      align: 'center',
    });

    slide.addText(stat.label, {
      x,
      y: 2.1,
      w: 2.2,
      h: 0.3,
      fontSize: 10,
      fontFace: 'Arial',
      color: COLORS.lightText,
      align: 'center',
    });
  });

  // Top changes
  const topChanges = metricChanges
    .filter(m => m.direction !== 'neutral')
    .sort((a, b) => Math.abs(b.percentChange) - Math.abs(a.percentChange))
    .slice(0, 4);

  if (topChanges.length > 0) {
    slide.addText('Top Changes', {
      x: 0.5,
      y: 2.8,
      w: 9,
      h: 0.4,
      fontSize: 16,
      fontFace: 'Arial',
      color: COLORS.primary,
      bold: true,
    });

    topChanges.forEach((change, index) => {
      const y = 3.3 + index * 0.5;
      const sign = change.percentChange > 0 ? '+' : '';
      const color = change.direction === 'up' ? COLORS.success : COLORS.danger;

      slide.addText(`${change.metric}: ${sign}${change.percentChange.toFixed(1)}%`, {
        x: 0.7,
        y,
        w: 8,
        h: 0.4,
        fontSize: 14,
        fontFace: 'Arial',
        color: color,
        bullet: { type: 'bullet', color: color },
      });
    });
  }

  addSlideFooter(slide, COLORS);
}

/**
 * Add significant changes slide
 */
function addSignificantChangesSlide(pres, aiInsights, COLORS) {
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  addSlideHeader(slide, 'Significant Changes', COLORS);

  // AI badge
  slide.addShape(pres.ShapeType.roundRect, {
    x: 0.5,
    y: 1.1,
    w: 0.6,
    h: 0.3,
    fill: { color: COLORS.accent },
  });

  slide.addText('AI', {
    x: 0.5,
    y: 1.12,
    w: 0.6,
    h: 0.26,
    fontSize: 10,
    fontFace: 'Arial',
    color: COLORS.white,
    align: 'center',
    bold: true,
  });

  const bulletPoints = aiInsights.significantChanges.slice(0, 6).map(change => ({
    text: change,
    options: {
      fontSize: 13,
      color: COLORS.text,
      bullet: { type: 'bullet', color: COLORS.primary },
      paraSpaceAfter: 5,
    },
  }));

  slide.addText(bulletPoints, {
    x: 0.5,
    y: 1.5,
    w: 9,
    h: 3.6,
    fontFace: 'Arial',
    valign: 'top',
  });

  addSlideFooter(slide, COLORS);
}

/**
 * Add recommendations and concerns slide
 */
function addRecommendationsSlide(pres, aiInsights, COLORS) {
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  addSlideHeader(slide, 'Recommendations & Concerns', COLORS);

  let currentY = 1.2;

  // Recommendations with card style
  if (aiInsights.recommendations?.length > 0) {
    slide.addShape(pres.ShapeType.roundRect, {
      x: 0.4,
      y: currentY,
      w: 9.2,
      h: 1.7,
      fill: { color: COLORS.white },
      line: { color: COLORS.success, width: 0.5 },
    });

    slide.addText('Recommendations', {
      x: 0.55,
      y: currentY + 0.1,
      w: 9,
      h: 0.35,
      fontSize: 14,
      fontFace: 'Arial',
      color: COLORS.success,
      bold: true,
    });

    const recBullets = aiInsights.recommendations.slice(0, 3).map(rec => ({
      text: rec,
      options: {
        fontSize: 11,
        color: COLORS.text,
        bullet: { type: 'bullet', color: COLORS.success },
        paraSpaceAfter: 3,
      },
    }));

    slide.addText(recBullets, {
      x: 0.55,
      y: currentY + 0.45,
      w: 8.9,
      h: 1.15,
      fontFace: 'Arial',
      valign: 'top',
    });

    currentY += 1.9;
  }

  // Areas of concern with card style
  if (aiInsights.areasOfConcern?.length > 0) {
    slide.addShape(pres.ShapeType.roundRect, {
      x: 0.4,
      y: currentY,
      w: 9.2,
      h: 1.7,
      fill: { color: COLORS.white },
      line: { color: COLORS.danger, width: 0.5 },
    });

    slide.addText('Areas of Concern', {
      x: 0.55,
      y: currentY + 0.1,
      w: 9,
      h: 0.35,
      fontSize: 14,
      fontFace: 'Arial',
      color: COLORS.danger,
      bold: true,
    });

    const concernBullets = aiInsights.areasOfConcern.slice(0, 3).map(concern => ({
      text: concern,
      options: {
        fontSize: 11,
        color: COLORS.text,
        bullet: { type: 'bullet', color: COLORS.danger },
        paraSpaceAfter: 3,
      },
    }));

    slide.addText(concernBullets, {
      x: 0.55,
      y: currentY + 0.45,
      w: 8.9,
      h: 1.15,
      fontFace: 'Arial',
      valign: 'top',
    });
  }

  addSlideFooter(slide, COLORS);
}

/**
 * Add comparison data table slide with themed styling
 */
function addComparisonTableSlide(pres, comparison, files, COLORS) {
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  addSlideHeader(slide, 'Detailed Changes', COLORS);

  // Transform summary data
  const metricChanges = Object.entries(comparison.summary || {}).slice(0, 8).map(([metric, data]) => {
    const labels = Object.keys(data).filter(k => !['absoluteChange', 'percentageChange', 'direction'].includes(k));
    return {
      metric: formatColumnName(metric),
      value1: data[labels[0]] || 0,
      value2: data[labels[1]] || 0,
      percentChange: data.percentageChange || 0,
      direction: data.direction || 'neutral',
    };
  });

  if (metricChanges.length === 0) {
    slide.addText('No comparable metrics found', {
      x: 0.5,
      y: 2.5,
      w: 9,
      h: 0.5,
      fontSize: 16,
      fontFace: 'Arial',
      color: COLORS.lightText,
      align: 'center',
    });
    addSlideFooter(slide, COLORS);
    return;
  }

  // Truncate filenames for column headers
  const truncate = (str, len) => str.length > len ? str.slice(0, len - 3) + '...' : str;

  // Header row with theme color
  const headerRow = [
    { text: 'Metric', options: { fill: { color: COLORS.primary }, color: COLORS.white, bold: true, fontSize: 10, align: 'center' } },
    { text: truncate(files[0]?.filename || 'File 1', 15), options: { fill: { color: COLORS.primary }, color: COLORS.white, bold: true, fontSize: 10, align: 'center' } },
    { text: truncate(files[1]?.filename || 'File 2', 15), options: { fill: { color: COLORS.primary }, color: COLORS.white, bold: true, fontSize: 10, align: 'center' } },
    { text: '% Change', options: { fill: { color: COLORS.primary }, color: COLORS.white, bold: true, fontSize: 10, align: 'center' } },
  ];

  // Data rows
  const dataRows = metricChanges.map((row, index) => {
    const changeColor = row.direction === 'up' ? COLORS.success : row.direction === 'down' ? COLORS.danger : COLORS.text;
    const sign = row.percentChange > 0 ? '+' : '';

    return [
      { text: row.metric, options: { fill: { color: index % 2 === 0 ? COLORS.background : COLORS.white }, fontSize: 9, align: 'left' } },
      { text: formatNumber(row.value1), options: { fill: { color: index % 2 === 0 ? COLORS.background : COLORS.white }, fontSize: 9, align: 'right' } },
      { text: formatNumber(row.value2), options: { fill: { color: index % 2 === 0 ? COLORS.background : COLORS.white }, fontSize: 9, align: 'right' } },
      { text: `${sign}${row.percentChange.toFixed(1)}%`, options: { fill: { color: index % 2 === 0 ? COLORS.background : COLORS.white }, color: changeColor, fontSize: 9, align: 'right', bold: true } },
    ];
  });

  const tableData = [headerRow, ...dataRows];

  slide.addTable(tableData, {
    x: 0.5,
    y: 1.3,
    w: 9,
    colW: [3, 2, 2, 2],
    rowH: 0.4,
    border: { type: 'solid', color: 'E2E8F0', pt: 0.5 },
    fontFace: 'Arial',
  });

  addSlideFooter(slide, COLORS);
}

/**
 * Add closing slide with premium branding
 */
function addComparisonClosingSlide(pres, files, COLORS) {
  const slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });

  // Gradient-effect background
  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 1.8,
    w: '100%',
    h: 2.4,
    fill: { color: COLORS.primary },
  });

  // Accent element
  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 1.8,
    w: '100%',
    h: 0.1,
    fill: { color: COLORS.accent },
  });

  slide.addText('Comparison Complete', {
    x: 0,
    y: 2.1,
    w: '100%',
    h: 0.8,
    fontSize: 38,
    fontFace: 'Arial',
    color: COLORS.white,
    bold: true,
    align: 'center',
  });

  slide.addText(`${files[0]?.filename || 'File 1'} vs ${files[1]?.filename || 'File 2'}`, {
    x: 0,
    y: 2.9,
    w: '100%',
    h: 0.5,
    fontSize: 16,
    fontFace: 'Arial',
    color: COLORS.white,
    align: 'center',
  });

  // Branding footer
  slide.addShape(pres.ShapeType.rect, {
    x: 0,
    y: 4.9,
    w: '100%',
    h: 0.02,
    fill: { color: COLORS.background },
  });

  slide.addText(BRAND_NAME, {
    x: 0,
    y: 5,
    w: '100%',
    h: 0.35,
    fontSize: 16,
    fontFace: 'Arial',
    color: COLORS.primary,
    bold: true,
    align: 'center',
  });

  slide.addText(BRAND_TAGLINE, {
    x: 0,
    y: 5.3,
    w: '100%',
    h: 0.25,
    fontSize: 10,
    fontFace: 'Arial',
    color: COLORS.lightText,
    align: 'center',
  });
}

/**
 * Format column name for display
 */
function formatColumnName(col) {
  return col
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Format number for display
 */
function formatNumber(value) {
  if (value === null || value === undefined) return '-';
  if (typeof value === 'number') {
    return value.toLocaleString(undefined, { maximumFractionDigits: 2 });
  }
  return String(value);
}
